name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH to EC2 and update code
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user          # or ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/your-discord-bot
            git pull origin main
            # Restart systemd service
            sudo systemctl restart discordbot.service
