name: Deploy Discord Bot to EC2

on:
  push:
    branches: [ main ]

env:
  REPO_DIR: "/home/ubuntu/discord-bot"

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.EC2_SSH_KEY }}
        known_hosts: 'just-a-placeholder'
        
    - name: Add EC2 to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
        
    - name: Deploy and restart bot
      run: |
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          # Handle system updates if needed
          if [ -f /var/run/reboot-required ]; then
            echo "System reboot required - performing now..."
            sudo reboot
            sleep 60  # Wait for reboot to complete
          fi
          
          # Clean existing directory if corrupted
          if [ -d "$REPO_DIR" ] && [ ! -d "$REPO_DIR/.git" ]; then
            echo "Removing corrupted directory..."
            rm -rf $REPO_DIR
          fi
          
          # Create directory structure
          mkdir -p $REPO_DIR
          cd $REPO_DIR
          
          # Clone or update repository
          if [ ! -d ".git" ]; then
            git clone https://github.com/${{ github.repository }}.git .
            python3 -m venv venv
          else
            git fetch origin
            git reset --hard origin/main
          fi
          
          # Verify requirements.txt exists
          if [ ! -f "requirements.txt" ]; then
            echo "requirements.txt missing! Creating default..."
            echo "discord.py>=2.0.0" > requirements.txt
          fi
          
          # Install dependencies
          source venv/bin/activate
          pip install -r requirements.txt
          
          # Restart bot
          tmux kill-session -t discord_bot 2>/dev/null || true
          tmux new -d -s discord_bot
          tmux send-keys -t discord_bot "cd $REPO_DIR && source venv/bin/activate && python3 bot.py" C-m
          
          echo "✅ Deployment successful!"
        EOF