name: Deploy to EC2

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "Host ec2
            HostName ${{ secrets.EC2_HOST }}
            User ${{ secrets.EC2_USER }}
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Pull latest code and restart bot
        run: |
          ssh ec2 "
            cd ~/discord-bot &&
            git pull origin main &&
            python3 -m pip install --upgrade pip &&
            pip3 install -r requirements.txt &&
            tmux kill-session -t discordbot || true &&
            tmux new-session -d -s discordbot 'python3 bot.py'
          "
